name: 'ColorRoller - Color Picker'
author: SamGoody
category: Forms
tags: [color, picker, hsv, hsl, hsg]
#docs: http://url.to.docs
demo: http://siteroller.net/projects/colorpicker/Demo
current: 0.41